#!/usr/bin/env bash

ANDROID_TOOL=android

# Use android.bat on cygwin
hash ${ANDROID_TOOL} 2>&-
if [ $? -ne 0 ]; then
    ANDROID_TOOL=android.bat
fi

if [ ! -e assets ]; then
    mkdir assets
fi
if [ ! -e assets/cinder_logo.png ]; then
    cp ../../data/cinder_logo.png assets
fi

${ANDROID_TOOL} update project --path . --name AndroidTest --target android-8

